### PR TITLE
v2-article-search is added automatically based on metadata #122

### LINKED ISSUE #122: Bug: [V2 Article Search] the search doesn't get appended correctly to pages
### Issue Type

Bug

### Summary

_No response_

### Priority

Blocker

### Description

While attempting to add the V2 Article Search block to the Magazine article template to meet this [requirement](https://github.com/aemsites/volvotrucks-na/issues/65), I noticed that the block fails to integrate correctly and does not appear on the page.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
2. Check the top of the page, above the Hero block, where the Search feature is expected to appear.

### Expected Results

The Search should appear above the Hero block.

### Actual Results

The Search is not appearing above the Hero block.

### Attachment

_No response_

### PR DESCRIPTION
**Pull request by jonatan-lledo-netcentric**
Fix #122

~To avoid a random network bug, it adds an additional check to confirm if it is a _v2-magazine_ template and if it also has loaded the Hero from the template.~

~If it's not a magazine template or the Hero is not loaded yet, it adds the block as the 1st element to the _main_ element.
if it's a magazine template and the Hero is loaded, then **waits** until the Hero is decorated to add the block above it.~

~Following Santi's suggestion, I moved the logic to `common.js` to add the `v2-article-search` like a sub-nav.~

~To do so is no longer needed add it from the Library. it is added, like a sub-nav, by checking metadata.~
After some updates/commits, the block can be added by metadata following the next step or manually as a regular block with its variants (black or gray).
 
In `metadata.xslx` file (or in the metadata block) if is present `article-search` with 1 of these 3 values, such as `default`, `black` or `gray`, then the block is added as the 1st element to the main element. this is checked in the v2-magazine template only.

URL for testing:

Demo page with v2-magazine template applied ~(not working anymore)~
- Before: https://main--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/magazine/magazine-article-demo
- After: https://122-bug-v2-article-search--volvotrucks-us--volvogroup.aem.page/drafts/jlledo/magazine/magazine-article-demo

Library page with v2-magazine template applied
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
- After: https://122-bug-v2-article-search--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template

Library page with v2-article-search without template ~(not needed, added by metadata)~
- Before: https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-article-search
- After: https://122-bug-v2-article-search--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-article-search

### CODE REVIEW

File: blocks/v2-article-search/v2-article-search.js [hunk 1]
```diff
@@ -244,37 +244,47 @@ const initializeSearchHandlers = (searchContainer) => {
   }
 };
 
+const decorateArticleSearch = async (block, section, main) => {
```
Comment (amglebihan) [inline blocks/v2-article-search/v2-article-search.js:247]: The other day, I reviewed how to resolve the bug and believe we can refactor and simplify this block of code. 
Rather than iterating through all mutations, we should directly check for the presence of `articleHero`.
Additionally, we could optimise performance by restricting the observer to monitor only `childList` changes on `main` with `subtree: false`. You can implement an early return when the `v2-magazine` class is not present, which would prevent unnecessary setup.
This is only an example, that would have to be adapted, but that might help.

```
export default async function decorate(block) {
  const main = block.closest('main');
  const section = block.closest(`.${containerClass}`);

  if (!document.body.classList.contains('v2-magazine')) {
    decorateArticleSearch(block, section, main);
    return;
  }

  const checkAndDecorate = () => {
    const articleHero = main.querySelector('.v2-magazine-article-hero__container');
    if (articleHero) {
      decorateArticleSearch(block, section, main);
      observer?.disconnect(); // Disconnect observer if it's defined
      return true;
    }
    return false;
  };

  const observer = new MutationObserver(() => checkAndDecorate());

  if (!checkAndDecorate()) {
    observer.observe(main, {
      childList: true,
      subtree: false,
    });
  }
}
```

**Comment by amglebihan** [comment]
@jonatan-lledo-netcentric I believe we should adjust the background color of the search input when other section backgrounds are used. 
article-search

**Comment by jonatan-lledo-netcentric** [comment]
> @jonatan-lledo-netcentric Not related to the reported bug, but I believe we should adjust the background color of the search input when other section backgrounds are used. article-search
> 
> Could you also update the Sidekick library metadata and include details about the required metadata configuration necessary for the block to be displayed?

I fixed it in the last [commit](https://github.com/aemsites/volvotrucks-na/pull/130/commits/7dbd8d2f61028db76eeed2b1c84705990d7858ba)

File: blocks/v2-article-search/v2-article-search.js (hunk 1 above)
Comment (jonatan-lledo-netcentric) [reply blocks/v2-article-search/v2-article-search.js]: the logic has been moved to common.js to be like a sub-nav block

File: scripts/common.js [hunk 2]
```diff
@@ -256,6 +256,23 @@ export async function loadLazy(doc) {
     header.appendChild(subnav);
   }
 
+  // to add the article search block by checking the metadata
```
Comment (alexiscoelho) [inline scripts/common.js:259]: Put all of this inside of a method please :)

Comment (jonatan-lledo-netcentric) [reply scripts/common.js:277]: done

**Review by amglebihan — APPROVED** [review]

**Review by santi-homps — APPROVED** [review]
