### PR TITLE
Magazine subscription Submission pop-up message error #240

### LINKED ISSUE #240: Magazine subscription Submission pop-up message error
### Issue Type

Bug

### Summary

[V2 Newsletter Block] Pop up message error

### Priority

Critical

### Description

We have a new page which includes the V2 Newsletter Block. There is a pop-up message that should appear but doesn't. Instead, we are seeing a message that looks like a code error. The issue is occurring in the live site.

// eslint-disable-next-line no-undef
logResult({ result: 'success' });

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Chrome v133.0.6943.99

### Steps to Reproduce

Go to https://www.volvotrucks.us/news-and-stories/volvo-trucks-stories/#subscribe-for-the-latest-from-volvo-trucks
1. Click on "Subscribe"
2. Wait for the page to scroll down to the newsletter subscription field
3. Enter your email address
4. Click "Submit"
5. Wait for the response

### Expected Results

A pop-up message thanking the customer for subscribing, keeping the user on the same page. "Thank you for subscribing to the latest updates from Volvo Trucks!" - similar to the experience on the bottom of the homepage of volvotrucks.us for the subscribe form: 

Image

### Actual Results

An error message is appearing 
// eslint-disable-next-line no-undef
logResult({ result: 'success' });

### Attachment

_No response_

### Notes
- We need to see why is not gathering the "success" or "error" to show the feedback message.
- **Check also in the Homepage why we are not getting any feedback message, since this may be related**

### PR DESCRIPTION
**Pull request by jonatan-lledo-netcentric**
### Fix

_V2 Forms_ block is looking for the 1st form on the page. This could be a problem on pages with more than 1 `form` element.

To fix that, this update encapsulates the `form` element inside the _V2 Forms_ block to let the author add any amount of this block or other forms.

#

Fix #240 

URL for testing:
- Before: https://main--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/
- After: https://240-magazine-subscription-error--volvotrucks-us--volvogroup.aem.page/news-and-stories/volvo-trucks-stories/

### CODE REVIEW

**Review by alan-le-bihan — APPROVED** [review]

File: blocks/v2-forms/v2-forms.js [hunk 1]
```diff
@@ -98,7 +99,7 @@ const addForm = async (block) => {
 
   block.style.display = displayValue;
 
-  const formObj = document.querySelector('form');
+  const formObj = document.querySelector(`.${blockName}__form`);
```
Comment (alexiscoelho) [inline blocks/v2-forms/v2-forms.js:102]: Why are you using `document.querySelector(` and not `block.querySelector(`?

**Review by alexiscoelho — CHANGES_REQUESTED** [review]

File: blocks/v2-forms/v2-forms.js (hunk 1 above)
Comment (jonatan-lledo-netcentric) [reply blocks/v2-forms/v2-forms.js:102]: it was not possible before because the block element was replaced by the form. now I keep it and we can use `block` instead of `document`

**Review by alexiscoelho — APPROVED** [review]

**Review by alan-le-bihan — APPROVED** [review]
